name: release

on:
  push:
    tags: 
      - "v*"

jobs:
  release:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@v4.2
      with:
        useOCIRegistry: true
        registry-url:  oci://ghcr.io/goneup/
        username: ${{ github.repository_owner }}
        access-token: ${{ secrets.GITHUB_TOKEN }}
        force: true
        chart-folder: .