name: release

on:
  push:
    tags: 
      - "v*"

jobs:
  release:
    name: Build and Publish Helm Chart
    runs-on: ubuntu-latest
    steps:
    - name: Push Helm chart to OCI compatible registry (Github)
      uses: bsord/helm-push@v4.1.0
      with:
        useOCIRegistry: true
        registry-url:  oci://ghcr.io/${{ github.repository }}
        username: goneup
        access-token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}
        force: true
        chart-folder: ./